apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserv1-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microserv1
  template:
    metadata:
      labels:
        app: microserv1
    spec:
      containers:
        - name: microserv1
          image: phongsos/microserv1:1
          imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserv3-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microserv3
  template:
    metadata:
      labels:
        app: microserv3
    spec:
      containers:
        - name: microserv1
          image: phongsos/microserv3:1
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: microserv1-service
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  type: ClusterIP
  selector:
    app: microserv1

---

apiVersion: v1
kind: Service
metadata:
  name: microserv3-service
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  type: ClusterIP
  selector:
    app: microserv3
